(setq devdocs-browser-major-mode-docs-alist
      '((c-mode           "c")
        (c++-mode         "c++")
        (clojure-mode     "clojure")
        (coffee-mode      "CoffeeScript")
        (common-lisp-mode "lisp")
        (cperl-mode       "perl")
        (css-mode         "css")
        (elixir-mode      "elixir")
        (enh-ruby-mode    "ruby")
        (erlang-mode      "erlang")
        (gfm-mode         "markdown")
        (go-mode          "go")
        (groovy-mode      "groovy")
        (haskell-mode     "haskell")
        (html-mode        "html")
        (java-mode        "java")
        (js2-mode         "javascript")
        (js3-mode         "javascript")
        (less-css-mode    "less")
        (lua-mode         "lua")
        (markdown-mode    "markdown")
        (perl-mode        "perl")
        (php-mode         "php")
        (processing-mode  "processing")
        (puppet-mode      "puppet")
        (python-mode      "python")
        (ruby-mode        "ruby")
        (sass-mode        "sass")
        (scala-mode       "scala")
        (tcl-mode          "tcl")))



(provide 'devdocs-browser-extras)
