(defun my-eww-macro-go-to-next-page ()
  (interactive)
  (setq last-command-event 19)
  (isearch-forward nil 1)
  (setq last-command-event 78)
  (isearch-printing-char 78 1)
  (setq last-command-event 101)
  (isearch-printing-char 101 1)
  (setq last-command-event 120)
  (isearch-printing-char 120 1)
  (setq last-command-event 13)
  (isearch-exit)
  (setq last-command-event 13)
  (shr-browse-url nil 13)
  (setq last-command-event 101))

;; TODO: why does this not generate as expected?
(defun my-eww-macro-go-to-prev-page ()
  (interactive)
  (setq last-command-event 13)
  (shrface-links-counsel)
  (setq last-command-event 13)
  (shr-browse-url nil 13)
  (setq last-command-event 101))

(defun my-eww-macro-clone-in-other-vterm-window ()
  (interactive)
  (setq last-command-event 119)
  (kill-new (get-text-property (point) 'shr-url))
  (setq last-command-event 134217743)
  (xc/switch-to-last-window)
  (setq last-command-event 99)
  (vterm--self-insert)
  (setq last-command-event 108)
  (vterm--self-insert)
  (setq last-command-event 111)
  (vterm--self-insert)
  (setq last-command-event 110)
  (vterm--self-insert)
  (setq last-command-event 101)
  (vterm--self-insert)
  (setq last-command-event 32)
  (vterm--self-insert)
  (setq last-command-event 25)
  (vterm-yank nil)
  (setq last-command-event 13)
  (vterm-send-C-j)
  (setq last-command-event 134217743)
  (xc/switch-to-last-window)
  (setq last-command-event 110)
  (shr-next-link)
  (setq last-command-event 110)
  (shr-next-link)
  (setq last-command-event 101))
;;; easy org-web-tools-wrapper for my use case
;;;;  eww macro
(defun my-eww-macro-eww-to-org-easy ()
  (interactive)
  (delete-file "/home/strangepr0gram/.config/emacs/data/keyfreq.lock")
  (setq last-command-event 119)
  (shr-maybe-probe-and-copy-url (get-text-property (point) 'shr-url))
  (setq last-command-event 134217743)
  (xc/switch-to-last-window)
  (delete-file "/home/strangepr0gram/.config/emacs/data/keyfreq.lock")
  (delete-file "/home/strangepr0gram/.config/emacs/data/keyfreq.lock")
  (setq last-command-event 13)
  (org-web-tools-insert-web-page-as-entry (yank))
  (setq last-command-event 13)
  (setq last-command-event 134217742)
  (org-next-visible-heading 1)
  (delete-file "/home/strangepr0gram/.config/emacs/data/keyfreq.lock")
  (setq last-command-event 134217744)
  (org-previous-visible-heading 1)
  (setq last-command-event 134217734)
  (org-forward-heading-same-level 1)
  (delete-file "/home/strangepr0gram/.config/emacs/data/keyfreq.lock")
  (setq last-command-event 134217743)
  ;; add
  ;;
  (crux-move-beginning-of-line 1)
  (kill-line)
  (xc/switch-to-last-window)
  (setq last-command-event 110)
  (shr-next-link)
  (delete-file "/home/strangepr0gram/.config/emacs/data/keyfreq.lock")
  (setq last-command-event 101))

;;;; more readable form


(defun my-eww-macro-clone-in-other-vterm-window ()
  (interactive)
  (setq last-command-event 119)
  (kill-new (get-text-property (point) 'shr-url))
  (setq last-command-event 134217743)
  (xc/switch-to-last-window)
  (setq last-command-event 99)
  (vterm--self-insert)
  (setq last-command-event 108)
  (vterm--self-insert)
  (setq last-command-event 111)
  (vterm--self-insert)
  (setq last-command-event 110)
  (vterm--self-insert)
  (setq last-command-event 101)
  (vterm--self-insert)
  (setq last-command-event 32)
  (vterm--self-insert)
  (setq last-command-event 25)
  (vterm-yank nil)
  (setq last-command-event 13)
  (vterm-send-C-j)
  (setq last-command-event 134217743)
  (xc/switch-to-last-window)
  (setq last-command-event 110)
  (shr-next-link)
  (setq last-command-event 110)
  (shr-next-link)
  (setq last-command-event 101))

;;;; my easier to read form




(provide 'eww-macros)
