(defun my-prog-mode-setup ()
  (interactive)
  (flycheck-mode)
  (page-break-lines-mode)
  (eldoc-mode)
  (ws-butler-mode)
  (electric-quote-local-mode)
  (electric-pair-local-mode)
  (electric-layout-mode)
  (smart-hungry-delete-default-prog-mode-hook)
  (outline-minor-mode)
  (hs-minor-mode)
  (symbol-overlay-mode)
  (goto-address-prog-mode)
  (outshine-mode)
  (smart-newline-mode)
  (hl-todo-mode)
  (prettify-symbols-mode)
  (setq-local scroll-margin 3)
  (auto-fill-mode)
  (aggressive-indent-mode)
  (dtrt-indent-mode)
  (bug-reference-prog-mode)
  (fic-mode)
  (setq-local fill-column 80)
  (display-fill-column-indicator-mode)
  (yas-minor-mode)
  ;; TODO: not implemented in reality yet
  (setq-local next-error-function #'flycheck-next-error-function))
